export const ACADEMY_INFO = {
  name: 'Sulekha Zenith Academy',
  tagline: 'Personal Guidance, Strong Foundation, Bright Future',
  owner: 'Ruma Nath',
  phone: '+91 7003489512',
  phoneRaw: '917003489512',
  email: 'rumanath.1996@gmail.com',
  location: 'Rajpur Sonarpur, West Bengal, India',
  mapCode: 'CC87+M8 Rajpur Sonarpur, West Bengal',
  mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3688.0!2d88.4!3d22.4!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sCC87%2BM8+Rajpur+Sonarpur!5e0!3m2!1sen!2sin!4v1700000000000',
  whatsappUrl: 'https://wa.me/917003489512',
  description: 'A nurturing home-based learning environment where every student receives personal attention and guidance to build strong academic foundations.',
};

export const COURSES = [
  {
    id: 'math',
    name: 'Mathematics',
    icon: '🧮',
    description: 'Build strong foundations in arithmetic, algebra, geometry, and problem-solving with step-by-step conceptual clarity.',
    classes: 'Class I – X',
    color: 'from-blue-500 to-indigo-600',
    overview: 'Comprehensive mathematics coaching covering number systems, algebra, geometry, mensuration, statistics, and problem-solving techniques.',
    topics: ['Number System & Arithmetic', 'Algebra & Equations', 'Geometry & Mensuration', 'Statistics & Probability', 'Trigonometry (IX–X)', 'Word Problems & Logical Reasoning'],
    method: 'Step-by-step concept building with daily practice, doubt clearing sessions, and regular revision tests.',
    examSupport: 'Board exam pattern practice, previous year question solving, and timed mock tests.',
  },
  {
    id: 'science',
    name: 'General Science',
    icon: '🔬',
    description: 'Explore the natural world through engaging explanations, experiments, and practical understanding of scientific concepts.',
    classes: 'Class I – X',
    color: 'from-green-500 to-emerald-600',
    overview: 'General science covering physics, chemistry, biology, and environmental science with focus on conceptual understanding.',
    topics: ['Physics Fundamentals', 'Chemistry Basics', 'Biology & Life Sciences', 'Environmental Science', 'Practical Applications', 'Scientific Reasoning'],
    method: 'Visual learning with diagrams, real-life examples, and simplified explanations for complex topics.',
    examSupport: 'Chapter-wise tests, diagram practice, and board exam preparation with model answers.',
  },
  {
    id: 'english',
    name: 'English',
    icon: '📖',
    description: 'Master grammar, comprehension, creative writing, and communication skills with confidence.',
    classes: 'Class I – XII',
    color: 'from-purple-500 to-violet-600',
    overview: 'Complete English language and literature coaching from primary to higher secondary level.',
    topics: ['Grammar & Composition', 'Reading Comprehension', 'Creative Writing', 'Literature & Poetry', 'Essay & Letter Writing', 'Communication Skills'],
    method: 'Interactive reading sessions, writing practice, grammar drills, and vocabulary building exercises.',
    examSupport: 'Board exam writing techniques, literature analysis practice, and grammar-focused revision.',
  },
  {
    id: 'bengali',
    name: 'Bengali',
    icon: '✍️',
    description: 'Develop proficiency in Bengali language, literature, grammar, and creative expression.',
    classes: 'Class I – XII',
    color: 'from-orange-500 to-amber-600',
    overview: 'Bengali language and literature coaching covering grammar, prose, poetry, and creative writing for all levels.',
    topics: ['Bengali Grammar (ব্যাকরণ)', 'Prose & Poetry Analysis', 'Creative Writing (রচনা)', 'Letter & Application Writing', 'Literature Appreciation', 'Comprehension & Summary'],
    method: 'Literature-based learning with emphasis on language appreciation, grammar mastery, and expressive writing.',
    examSupport: 'Board exam answer writing techniques, literature analysis, and grammar-focused preparation.',
  },
  {
    id: 'history',
    name: 'History',
    icon: '🏛️',
    description: 'Journey through time with engaging narratives that make historical events memorable and meaningful.',
    classes: 'Class V – XII',
    color: 'from-red-500 to-rose-600',
    overview: 'History coaching covering Indian and world history with focus on understanding events, causes, and impacts.',
    topics: ['Ancient Indian History', 'Medieval India', 'Modern Indian History', 'World History', 'Indian Freedom Movement', 'Social & Cultural History'],
    method: 'Storytelling approach with timelines, map work, and connecting historical events to present-day relevance.',
    examSupport: 'Answer structuring for board exams, date-event correlation practice, and long-answer writing skills.',
  },
  {
    id: 'geography',
    name: 'Geography',
    icon: '🌍',
    description: 'Understand our world through maps, climate patterns, landforms, and human geography.',
    classes: 'Class V – XII',
    color: 'from-teal-500 to-cyan-600',
    overview: 'Geography coaching covering physical, human, and economic geography with practical map skills.',
    topics: ['Physical Geography', 'Indian Geography', 'World Geography', 'Map Reading & Skills', 'Climate & Weather', 'Human & Economic Geography'],
    method: 'Visual learning with maps, diagrams, and real-world examples to understand geographical concepts.',
    examSupport: 'Map pointing practice, diagram-based answers, and board exam pattern preparation.',
  },
  {
    id: 'gk',
    name: 'General Knowledge',
    icon: '💡',
    description: 'Stay curious and informed with current affairs, science facts, and general awareness topics.',
    classes: 'Class I – X',
    color: 'from-pink-500 to-fuchsia-600',
    overview: 'General knowledge and awareness building covering current affairs, science, culture, and world knowledge.',
    topics: ['Current Affairs', 'Science & Technology', 'Indian Culture & Heritage', 'Sports & Awards', 'World Facts', 'Environmental Awareness'],
    method: 'Quiz-based learning, newspaper discussions, and interactive knowledge-sharing sessions.',
    examSupport: 'Scholarship exam preparation, quiz competitions, and general awareness building.',
  },
];

export const FEATURES = [
  {
    icon: '👩‍🏫',
    title: 'Personal Attention',
    description: 'Every student receives individual focus and customized guidance tailored to their learning pace.',
  },
  {
    icon: '👥',
    title: 'Small Batches',
    description: 'Limited students per batch ensures quality teaching and better student-teacher interaction.',
  },
  {
    icon: '🏠',
    title: 'Home-Based Learning',
    description: 'Comfortable and familiar environment that helps students feel relaxed and focused.',
  },
  {
    icon: '📱',
    title: 'Parent Communication',
    description: 'Regular updates to parents about progress, attendance, and areas for improvement.',
  },
  {
    icon: '📝',
    title: 'Regular Assessments',
    description: 'Frequent tests and evaluations to track progress and identify areas needing attention.',
  },
  {
    icon: '💪',
    title: 'Concept Clarity',
    description: 'Focus on understanding concepts deeply rather than rote memorization for lasting knowledge.',
  },
  {
    icon: '📚',
    title: 'Complete Syllabus',
    description: 'Thorough coverage of school syllabus with additional practice materials and resources.',
  },
  {
    icon: '🌟',
    title: 'Exam Preparation',
    description: 'Special focus on exam techniques, time management, and strategic preparation methods.',
  },
];

export const STATS = [
  { label: 'Students Taught', value: 500, suffix: '+' },
  { label: 'Satisfaction Rate', value: 95, suffix: '%' },
  { label: 'Years Experience', value: 10, suffix: '+' },
  { label: 'Dedication', value: 100, suffix: '%' },
];

export const NAV_LINKS = [
  { href: '#home', label: 'Home' },
  { href: '#about', label: 'About' },
  { href: '#courses', label: 'Courses' },
  { href: '#why-us', label: 'Why Us' },
  { href: '#reviews', label: 'Reviews' },
  { href: '#gallery', label: 'Gallery' },
  { href: '#contact', label: 'Contact' },
];
