export const ACADEMY_INFO = {
  name: 'Sulekha Zenith Academy',
  tagline: 'Personal Guidance, Strong Foundation, Bright Future',
  owner: 'Ruma Nath',
  phone: '+91 7003489512',
  phoneRaw: '917003489512',
  email: 'rumanath.1996@gmail.com',
  location: 'Rajpur Sonarpur, West Bengal, India',
  mapCode: 'CC87+M8 Rajpur Sonarpur, West Bengal',
  mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3688.0!2d88.4!3d22.4!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sCC87%2BM8+Rajpur+Sonarpur!5e0!3m2!1sen!2sin!4v1700000000000',
  whatsappUrl: 'https://wa.me/917003489512',
  description: 'A nurturing home-based learning environment where every student receives personal attention and guidance to build strong academic foundations.',
};

export const SCHOOL_COURSES = [
  {
    id: 'math',
    name: 'Mathematics',
    icon: '🧮',
    description: 'Build strong foundations in arithmetic, basic algebra, geometry, logical reasoning, and problem-solving skills.',
    classes: 'Class I – V',
    category: 'school' as const,
    color: 'from-blue-500 to-indigo-600',
    overview: 'Comprehensive mathematics coaching covering number systems, basic algebra, geometry, logical reasoning, and problem-solving techniques.',
    topics: ['Arithmetic', 'Basic Algebra', 'Geometry', 'Logical Reasoning', 'Problem-Solving Skills'],
    method: 'Step-by-step concept building with daily practice, doubt clearing sessions, and regular revision tests.',
    examSupport: 'Board exam pattern practice, previous year question solving, and timed mock tests.',
  },
  {
    id: 'science',
    name: 'General Science',
    icon: '🔬',
    description: 'Understand basic scientific concepts through engaging explanations, experiments, and practical learning.',
    classes: 'Class I – VI',
    category: 'school' as const,
    color: 'from-green-500 to-emerald-600',
    overview: 'General science covering physics, chemistry, biology, and environmental science with focus on conceptual understanding through experiments.',
    topics: ['Physics Fundamentals', 'Chemistry Basics', 'Biology & Life Sciences', 'Environmental Science', 'Practical Experiments', 'Scientific Reasoning'],
    method: 'Visual learning with diagrams, real-life examples, and simplified explanations for complex topics.',
    examSupport: 'Chapter-wise tests, diagram practice, and exam preparation with model answers.',
  },
  {
    id: 'english',
    name: 'English',
    icon: '📖',
    description: 'Develop grammar, comprehension, writing, vocabulary, and communication skills.',
    classes: 'Class I – XII',
    category: 'school' as const,
    color: 'from-purple-500 to-violet-600',
    overview: 'Complete English language and literature coaching from primary to higher secondary level.',
    topics: ['Grammar & Composition', 'Reading Comprehension', 'Creative Writing', 'Vocabulary Building', 'Literature & Poetry', 'Communication Skills'],
    method: 'Interactive reading sessions, writing practice, grammar drills, and vocabulary building exercises.',
    examSupport: 'Board exam writing techniques, literature analysis practice, and grammar-focused revision.',
  },
  {
    id: 'bengali',
    name: 'Bengali',
    icon: '✍️',
    description: 'Build proficiency in Bengali language, literature, grammar, writing, and expression.',
    classes: 'Class I – XII',
    category: 'school' as const,
    color: 'from-orange-500 to-amber-600',
    overview: 'Bengali language and literature coaching covering grammar, prose, poetry, and creative writing for all levels.',
    topics: ['Bengali Grammar (ব্যাকরণ)', 'Prose & Poetry Analysis', 'Creative Writing (রচনা)', 'Letter & Application Writing', 'Literature Appreciation', 'Expression & Communication'],
    method: 'Literature-based learning with emphasis on language appreciation, grammar mastery, and expressive writing.',
    examSupport: 'Board exam answer writing techniques, literature analysis, and grammar-focused preparation.',
  },
  {
    id: 'history',
    name: 'History',
    icon: '🏛️',
    description: 'Explore historical events, civilizations, freedom movements, and cultural heritage.',
    classes: 'Class I – XII',
    category: 'school' as const,
    color: 'from-red-500 to-rose-600',
    overview: 'History coaching covering Indian and world history with focus on understanding events, civilizations, and cultural heritage.',
    topics: ['Ancient Civilizations', 'Medieval India', 'Modern Indian History', 'Freedom Movements', 'World History', 'Cultural Heritage'],
    method: 'Storytelling approach with timelines, map work, and connecting historical events to present-day relevance.',
    examSupport: 'Answer structuring for board exams, date-event correlation practice, and long-answer writing skills.',
  },
  {
    id: 'geography',
    name: 'Geography',
    icon: '🌍',
    description: 'Learn physical geography, human geography, maps, climate, environment, and world geography.',
    classes: 'Class I – XII',
    category: 'school' as const,
    color: 'from-teal-500 to-cyan-600',
    overview: 'Geography coaching covering physical, human, and world geography with practical map skills.',
    topics: ['Physical Geography', 'Human Geography', 'Maps & Navigation', 'Climate & Environment', 'World Geography', 'Indian Geography'],
    method: 'Visual learning with maps, diagrams, and real-world examples to understand geographical concepts.',
    examSupport: 'Map pointing practice, diagram-based answers, and board exam pattern preparation.',
  },
  {
    id: 'gk',
    name: 'General Knowledge',
    icon: '💡',
    description: 'Stay informed about current affairs, science facts, technology, sports, and general awareness topics.',
    classes: 'Class I – X',
    category: 'school' as const,
    color: 'from-pink-500 to-fuchsia-600',
    overview: 'General knowledge and awareness building covering current affairs, science, technology, sports, and world knowledge.',
    topics: ['Current Affairs', 'Science & Technology', 'Sports & Awards', 'Indian Culture & Heritage', 'World Facts', 'Environmental Awareness'],
    method: 'Quiz-based learning, newspaper discussions, and interactive knowledge-sharing sessions.',
    examSupport: 'Scholarship exam preparation, quiz competitions, and general awareness building.',
  },
];

export const HIGHER_ED_COURSES = [
  {
    id: 'bengali-ug-pg',
    name: 'Bengali (Honours & General)',
    icon: '📚',
    description: 'Comprehensive Bengali literature and language coaching for undergraduate and postgraduate students.',
    classes: 'UG & PG (Master\'s)',
    category: 'higher' as const,
    color: 'from-orange-500 to-amber-600',
    overview: 'In-depth Bengali literature and language studies covering classical and modern texts, grammar, poetry, literary criticism, and linguistics for Honours and General degree students.',
    topics: ['Bengali Literature', 'Bengali Grammar', 'Poetry', 'Literary Criticism', 'Linguistics', 'Modern & Classical Bengali Texts'],
    method: 'Analytical reading, text-based discussions, essay writing practice, and critical analysis of literary works.',
    examSupport: 'University exam preparation, answer writing techniques, and previous year question analysis.',
  },
  {
    id: 'polsci-ug',
    name: 'Political Science (General)',
    icon: '🏛️',
    description: 'Political theory, Indian government, public administration, and international relations for UG students.',
    classes: 'Undergraduate (UG)',
    category: 'higher' as const,
    color: 'from-indigo-500 to-blue-600',
    overview: 'Political Science coaching covering political theory, Indian government and politics, public administration, international relations, and comparative politics.',
    topics: ['Political Theory', 'Indian Government & Politics', 'Public Administration', 'International Relations', 'Comparative Politics'],
    method: 'Conceptual discussions, case studies, current political analysis, and structured answer writing practice.',
    examSupport: 'University exam preparation, essay structuring, and analytical answer writing techniques.',
  },
  {
    id: 'sociology-ug',
    name: 'Sociology & Anthropology (General)',
    icon: '👥',
    description: 'Social structure, Indian society, cultural anthropology, and human evolution for UG students.',
    classes: 'Undergraduate (UG)',
    category: 'higher' as const,
    color: 'from-emerald-500 to-teal-600',
    overview: 'Sociology and Anthropology coaching covering social structure, social change, Indian society, cultural anthropology, human evolution, and tribal studies.',
    topics: ['Social Structure', 'Social Change', 'Indian Society', 'Cultural Anthropology', 'Human Evolution', 'Tribal Studies'],
    method: 'Discussion-based learning, case studies, fieldwork concepts, and analytical writing practice.',
    examSupport: 'University exam preparation, answer structuring, and conceptual clarity building.',
  },
  {
    id: 'history-ug',
    name: 'History (General)',
    icon: '📜',
    description: 'Ancient, medieval, modern, Indian, and world history for undergraduate students.',
    classes: 'Undergraduate (UG)',
    category: 'higher' as const,
    color: 'from-red-500 to-rose-600',
    overview: 'History coaching for UG students covering ancient, medieval, and modern history along with Indian and world history in depth.',
    topics: ['Ancient History', 'Medieval History', 'Modern History', 'Indian History', 'World History'],
    method: 'Analytical approach with source-based learning, timeline mapping, and critical essay writing.',
    examSupport: 'University exam preparation, long-answer writing skills, and previous year question practice.',
  },
  {
    id: 'geography-ug',
    name: 'Geography (General)',
    icon: '🌎',
    description: 'Physical geography, human geography, geomorphology, and environmental geography for UG students.',
    classes: 'Undergraduate (UG)',
    category: 'higher' as const,
    color: 'from-cyan-500 to-sky-600',
    overview: 'Geography coaching for UG students covering physical geography, human geography, geomorphology, environmental geography, and GIS basics.',
    topics: ['Physical Geography', 'Human Geography', 'Geomorphology', 'Environmental Geography', 'GIS & Mapping Basics'],
    method: 'Map-based learning, diagram practice, fieldwork concepts, and analytical answer writing.',
    examSupport: 'University exam preparation, map work practice, and diagram-based answer techniques.',
  },
];

export const COURSES = [...SCHOOL_COURSES, ...HIGHER_ED_COURSES];

export const FEATURES = [
  {
    icon: '👩‍🏫',
    title: 'Personal Attention',
    description: 'Every student receives individual focus and customized guidance tailored to their learning pace.',
  },
  {
    icon: '👥',
    title: 'Small Batches',
    description: 'Limited students per batch ensures quality teaching and better student-teacher interaction.',
  },
  {
    icon: '🏠',
    title: 'Home-Based Learning',
    description: 'Comfortable and familiar environment that helps students feel relaxed and focused.',
  },
  {
    icon: '📱',
    title: 'Parent Communication',
    description: 'Regular updates to parents about progress, attendance, and areas for improvement.',
  },
  {
    icon: '📝',
    title: 'Regular Assessments',
    description: 'Frequent tests and evaluations to track progress and identify areas needing attention.',
  },
  {
    icon: '💪',
    title: 'Concept Clarity',
    description: 'Focus on understanding concepts deeply rather than rote memorization for lasting knowledge.',
  },
  {
    icon: '📚',
    title: 'Complete Syllabus',
    description: 'Thorough coverage of school syllabus with additional practice materials and resources.',
  },
  {
    icon: '🌟',
    title: 'Exam Preparation',
    description: 'Special focus on exam techniques, time management, and strategic preparation methods.',
  },
];

export const TEACHING_START_YEAR = 2018;

export const STATS = [
  { label: 'Students Taught', value: 10, suffix: '+' },
  { label: 'Satisfaction Rate', value: 95, suffix: '%' },
  { label: 'Years Experience', value: new Date().getFullYear() - TEACHING_START_YEAR, suffix: '+' },
  { label: 'Dedication', value: 100, suffix: '%' },
];

export const NAV_LINKS = [
  { href: '#home', label: 'Home' },
  { href: '#about', label: 'About' },
  { href: '#courses', label: 'Courses' },
  { href: '#why-us', label: 'Why Us' },
  { href: '#reviews', label: 'Reviews' },
  { href: '#gallery', label: 'Gallery' },
  { href: '#contact', label: 'Contact' },
];
